default_method_hyperparameters:
  openai_key: sk-
  claude_key: 
  mutate_model_path: openchat/openchat-3.5-1210
  use_local_model: true
  max_query: 1000
  max_jailbreak: 1
  max_iteration: 100
  energy: 1
  seed_selection_strategy: round_robin
  max_new_tokens: 512
  seed_path: baselines/gptfuzz/GPTFuzzer.csv
  targets_path: data/optimizer_targets/harmbench_targets_text.json
  num_gpus: 4
<model_name1>:
  target_model: <model_name1>['model']

